services:
  postgres:
    image: postgres:17-alpine
    container_name: corebanking-postgres
    environment:
      POSTGRES_DB: corebanking
      POSTGRES_USER: corebanking
      POSTGRES_PASSWORD: corebanking
    ports:
      - "5432:5432"
    volumes:
      - corebanking-pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management
    container_name: corebanking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: corebanking
      RABBITMQ_DEFAULT_PASS: corebanking

volumes:
  corebanking-pgdata:

