spring.application.name=corebanking

spring.datasource.url=jdbc:postgresql://localhost:5432/corebanking
spring.datasource.username=corebanking
spring.datasource.password=corebanking

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=com.hmetsallik.corebanking.common