spring.application.name=corebanking

spring.datasource.url=jdbc:postgresql://localhost:5432/corebanking
spring.datasource.username=corebanking
spring.datasource.password=corebanking

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=corebanking
spring.rabbitmq.password=corebanking
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=500ms
spring.rabbitmq.template.retry.max-retries=3
spring.rabbitmq.template.retry.multiplier=2

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-handlers-package=com.hmetsallik.corebanking.common

